// <auto-generated />
namespace BitstampTradeBot.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CurrencyPair_FK_In_Order_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CurrencyPair_FK_In_Order_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "201802131753597_CurrencyPair_FK_In_Order_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
